#!/usr/bin/env bash

cd $HOME

home_setup() {
	mkdir -p -v mnt/secspace opt var/{syncity,dl} tmp
}

package_install() {
	apt install ssh htop tree git tmux screen vcsh mr keepassx zsh mc lfm zim python-pip
	sudo pip install --system py3status
}

desktop() {
	echo "choose i3 config for desktop"
}

laptop() {
	echo "choose i3 config for laptop"
}

notmine() {
	echo "take care"
}

#vcsh clone https://gitlab.com/fakhraee/dot-mr.git mr
