#!/usr/bin/env bash

cd $HOME

home_setup() {
	mkdir -p -v bin $HOME/mnt/cry opt/w32 $HOME/var/{dl,git} tmp
}

package_install() {
	sudo apt install ssh htop tree git tmux screen vcsh mr cryfs zsh mc zim grc \
                   xtail neovim neomutt libterm-extendedcolor-perl proxychins \
                   tor highlight libnotify-bin remmina remmina-plugin-rdp \
                   libfribidi-bin kbdd rxvt-unicode mpd colordiff whois
}

desktop() {
	echo "choose i3 config for desktop"
}

laptop() {
	echo "choose i3 config for laptop"
}

notmine() {
	echo "take care"
}

#vcsh clone https://gitlab.com/fakhraee/dot-mr.git mr
